### ISSUE TITLE
Add list of apps that use djinni

### ISSUE THREAD

**Issue by jothepro** [cross-language-cpp/cross-language-cpp.github.io#6]
As a project maintainer I'd like to promote djinni as "not yet dead" and "more popular than you might think" in this repository, to attract new users & contributors. To do so, I'd like to add a section like "**These companies rely on djinni**" or "**these apps rely on djinni**" to the README.
This will help us as a community to have a higher chance to thrive in the long term.

## TODO:
- [ ] collect an initial list of apps/developers using djinni that are willing to be promoted on our repo (doesn't matter if they already use our repo in the first place)
    - [ ] ask @a4z & @bojanin if their companies would be willing to be listed
    - [ ] I am planning to publish an app, but it's a toy project and will probably take a while to go public... :P
    - [ ] contact Dave Hagedorn if he'd like **TextNow** to be listed. (thanks to @a4z for [sharing this podcast](https://cppcast.com/telephony-dave-hagedorn/))
- [ ] decide if and how the collected information should be presented (list of companies vs list of explicit apps)
- [ ] prepare a first version of the listing
